version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Vienna"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
    groups:
      angular:
        patterns:
          - "@angular/*"
      capacitor:
        patterns:
          - "@capacitor/*"
          - "@capacitor-community/*"
      lint-and-test-tooling:
        patterns:
          - "@eslint/*"
          - "@cloudflight/*"
          - "eslint"
          - "vitest"
          - "@vitest/*"
      styling-tooling:
        patterns:
          - "tailwindcss"
          - "postcss"
          - "autoprefixer"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:30"
      timezone: "Europe/Vienna"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
    groups:
      github-actions:
        patterns:
          - "*"