name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          package-manager-cache: false

      - name: Install dependencies
        run: npm install

      - name: Prepare PowerSync assets
        run: npm run powersync:setup

      - name: Run lint (generate report)
        run: |
          mkdir -p reports
          set -o pipefail
          npm run lint 2>&1 | tee reports/eslint-report.log

      - name: Upload lint report artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: lint-report
          path: reports/eslint-report.log

  component-test:
    name: Component Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          package-manager-cache: false

      - name: Install dependencies
        run: npm install

      - name: Run component tests (generate log)
        run: |
          mkdir -p reports
          set -o pipefail
          npm run test:component 2>&1 | tee reports/component-test.log

      - name: Upload component test artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: component-test-report
          path: reports/component-test.log

  e2e-test:
    name: Cypress E2E Tests
    needs: [lint, component-test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          package-manager-cache: false

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          install: false
          build: npm run build
          start: npm run start
          wait-on: 'http://localhost:4200'
          # default timeout is 60 seconds. wait-on-timeout defines how long we should wait for the server before failing
          wait-on-timeout: 120

      - name: Upload Cypress Screenshots (on failure)
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress Videos (on failure)
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

